### ISSUE TITLE
Errors since upgrading to 0.2.5

### ISSUE THREAD

**Issue by borisnieuwenhuis** [Woody4618/github-actions#5]
both the workflow and actions how the following error:

```
2025-04-16 11:48:30 (10.9 MB/s) - ‘criterion-v2.3.3-linux-x86_64.tar.bz2’ saved [677858/677858]

+ tar --strip-components 1 -jxf criterion-v2.3.3-linux-x86_64.tar.bz2
+ ./platform-tools/rust/bin/rustc --version
+ ./platform-tools/rust/bin/rustc --print sysroot
+ set +e
+ rustup toolchain uninstall solana
info: uninstalling toolchain 'solana'
info: toolchain 'solana' uninstalled
+ set -e
+ rustup toolchain link solana platform-tools/rust
+ exit 0
   Compiling proc-macro2 v1.0.94
   Compiling unicode-ident v1.0.18
   Compiling version_check v0.9.5
   Compiling typenum v1.18.0
error[E0412]: cannot find type `SourceFile` in crate `proc_macro`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.94/src/wrapper.rs:366:26
    |
366 |     Compiler(proc_macro::SourceFile),
    |                          ^^^^^^^^^^ not found in `proc_macro`
    |
help: consider importing one of these structs
    |
1   + use crate::SourceFile;
    |
1   + use crate::fallback::SourceFile;
    |
help: if you import `SourceFile`, refer to it directly
    |
366 -     Compiler(proc_macro::SourceFile),
366 +     Compiler(SourceFile),
    |

error[E0412]: cannot find type `SourceFile` in crate `proc_macro`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.94/src/wrapper.rs:372:32
    |
372 |     fn nightly(sf: proc_macro::SourceFile) -> Self {
    |                                ^^^^^^^^^^ not found in `proc_macro`
    |
help: consider importing one of these structs
    |
1   + use crate::SourceFile;
    |
1   + use crate::fallback::SourceFile;
    |
help: if you import `SourceFile`, refer to it directly
    |
372 -     fn nightly(sf: proc_macro::SourceFile) -> Self {
372 +     fn nightly(sf: SourceFile) -> Self {
    |

error[E0599]: no method named `source_file` found for reference `&proc_macro::Span` in the current scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.94/src/wrapper.rs:462:56
    |
462 |             Span::Compiler(s) => SourceFile::nightly(s.source_file()),
    |                                                        ^^^^^^^^^^^
    |
help: there is a method `source` with a similar name
    |
462 -             Span::Compiler(s) => SourceFile::nightly(s.source_file()),
462 +             Span::Compiler(s) => SourceFile::nightly(s.source()),
    |

   Compiling generic-array v0.14.7
Some errors have detailed explanations: E0412, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `proc-macro2` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Building IDL failed. Run `ANCHOR_LOG=true anchor idl build` to see the logs.
Error: Process completed with exit code 1.
```

**Comment by borisnieuwenhuis** [comment]
Now I see a new error

```
22s
Run solana-developers/github-actions/run-tests@v0.2.5
  with:
    solana_version: 2.[1](https://github.com/crunchdao/crunchdao-protocol/actions/runs/14642398135/job/41087757403?pr=69#step:6:1).0
    anchor_version: 0.31.0
    program: coordinator
  env:
    SOLANA_VERSION: [2](https://github.com/crunchdao/crunchdao-protocol/actions/runs/14642398135/job/41087757403?pr=69#step:6:2).1.0
    ANCHOR_VERSION: 0.[3](https://github.com/crunchdao/crunchdao-protocol/actions/runs/14642398135/job/41087757403?pr=69#step:6:3)1.0
Run actions/cache@v3
  with:
    path: ./node_modules/
    key: node-modules-Linux-build-v0.1-0.31.0-2.1.0
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    SOLANA_VERSION: 2.1.0
    ANCHOR_VERSION: 0.31.0
Cache not found for input keys: node-modules-Linux-build-v0.1-0.31.0-2.1.0
Run yarn install
  yarn install
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SOLANA_VERSION: 2.1.0
    ANCHOR_VERSION: 0.31.0
yarn install v1.22.22
warning package.json: No license field
warning @crunchdao/crunch-client@0.9.5: No license field
[1/[4](https://github.com/crunchdao/crunchdao-protocol/actions/runs/14642398135/job/41087757403?pr=69#step:6:4)] Resolving packages...
[2/4] Fetching packages...
error @solana/codecs-numbers@2.1.0: The engine "node" is incompatible with this module. Expected version ">=20.1[8](https://github.com/crunchdao/crunchdao-protocol/actions/runs/14642398135/job/41087757403?pr=69#step:6:8).0". Got "18.20.8"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
Run echo "Tests failed! Check the logs above for details."
Tests failed! Check the logs above for details.
Error: Process completed with exit code 1.
```

**Comment by Woody4618** [comment]
Hey, the first one should be fixed now when you upgrade to the newest anchor version and running cargo update: https://github.com/solana-foundation/anchor/releases 0.31.1. The problem comes from procmarco2 which is updated since anchor idl  build uses rust nightly sadly. This will be changed in the future. For now there is a new version 

Second one i will investigate. Do you have a repository in which that happens? Looks like https://github.com/crunchdao/crunchdao-protocol is private

**Comment by borisnieuwenhuis** [comment]
@Woody4618 yes it also happens in my debug project https://github.com/borisnieuwenhuis/hello_solana3/actions/runs/14611300824/job/40989721084

**Comment by Woody4618** [comment]
Second one @solana/codecs-numbers@2.1.0 is fixed in 0.2.7 of the test workflow now. Thank you very much for reporting this!  I increased the installed node version to 20 in the test workflow. See release: https://github.com/solana-developers/github-workflows/releases/tag/v0.2.7  

https://github.com/Woody4618/hello_solana3/actions/runs/14665295415 Here is a successful build. I also had to update anchor to 0.31.1 and cargo update and change the test command from pnpm to yarn. Do you need pnpm support? Yarn works fine as well right?
